name: qfm-env
channels: 
  - defaults
dependencies: 
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - notebook
  - pip:
    - qiskit==0.41.0  
    - qiskit-machine-learning
    - qiskit-ibm-runtime
    - pennylane 
    - pennylane-qiskit
    - pennylane-lightning
    - torch
    - torchvision
    - pylatexenc
    - python-dotenv
 


 

